### ISSUE TITLE
Default behavior when calendar_dates.txt is missing

### ISSUE THREAD

**Issue by sfwatergit** [matsim-org/pt2matsim#1]
Some GTFS files do not contain a calendar dates file. This shouldn't really affect the mapping, since the effective date range is nowhere verified (though this could later be a possible feature). Probably should just log a warning and move on.

**Comment by polettif** [comment]
That's right, calendar_dates.txt is now handled like frequencies.txt or shapes.txt. An info (instead of a warning) is logged since the file is optional.
