### ISSUE TITLE
Accept valid GTFS feeds without calendar.txt

### ISSUE THREAD

**Issue by thakoch** [matsim-org/pt2matsim#100]
There are quite a few GTFS feeds without calendar.txt, currently pt2matsim fails on the false assumption that calendar.txt is a required file. 
Per GTFS reference documentation, it's only conditionally required and it's also valid to manually include all valid dates using calendar_dates.txt.
https://developers.google.com/transit/gtfs/reference#calendartxt

https://github.com/matsim-org/pt2matsim/blob/344f8f4e4165515ebe687d8171cf1279ce9c1946/src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java#L145

**Comment by polettif** [comment]
You're absolutely right. Taking this further, exceptions might not be the best way to indicate missing files anyways since not all of them are necessary for a valid MATSim schedule.
