### ISSUE TITLE
artificial lines

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/pt2matsim#102]
I have tried PublicTransitMapper in pt2matsim. 226 "artificial lines" have been created. I wonder if the artificial lines are inescapable? Or there are other problems? Here is my network in Via:
![image](https://user-images.githubusercontent.com/35290093/76282314-55c74b80-62d2-11ea-8fdb-bb62633a3208.png)
      The red lines are "artificial lines" .And there are about 126 bus lines with 17183 links in my network. Do you have some advice?
      Hope to get your early reply!

**Comment by polettif** [comment]
I'll refer to the [wiki entry on plausibility warnings](https://github.com/matsim-org/pt2matsim/wiki/Check-Mapped-Schedule-Plausibility#how-to-handle-warnings) which also applies if there are too many artificial links. I don't know how many routes your schedule has, your network doesn't look too bad though. There might be some network links missing (or they have the wrong mode) or stops are too far from any link. I guess there's no way around looking at each artificial link cluster closely and determine what's wrong with the network there.

**Comment by jiao1997** [comment]
> I'll refer to the [wiki entry on plausibility warnings](https://github.com/matsim-org/pt2matsim/wiki/Check-Mapped-Schedule-Plausibility#how-to-handle-warnings) which also applies if there are too many artificial links. I don't know how many routes your schedule has, your network doesn't look too bad though. There might be some network links missing (or they have the wrong mode) or stops are too far from any link. I guess there's no way around looking at each artificial link cluster closely and determine what's wrong with the network there.

Thank you very much. There are 126 bus lines in my schedule. And I guess there are some problems in my network. I convert it from osm with my own python program. My question is that is the links in osm also unidirectional，just like MATSim.

**Comment by polettif** [comment]
I'm not sure I understand your question but most links (or rather "ways") in osm are bidirectional. Only ways with the [tag oneway](https://wiki.openstreetmap.org/wiki/Key:oneway) are unidirectional.

**Comment by jiao1997** [comment]
> I'm not sure I understand your question but most links (or rather "ways") in osm are bidirectional. Only ways with the [tag oneway](https://wiki.openstreetmap.org/wiki/Key:oneway) are unidirectional.

Thank you very much! I have solve the problem and have created the transit network. What is more,
the departure time of the specific vehicle is needed. And I only have the bus trajectory data(contains bus line, latitude, longitude and positioning time). As we all known , when a bus arrives at the terminal, it goes back and repeats the route. Such as: vehicle 1 has a departure from the starting station at 7:00. Then the bus goes back to the starting station and starts the next cycle at 8:00. Are the two departures of one vehicle had to be defined? If yes, do you have some advice to get the departure.
     Hope to get your early reply!
                                                                                                                                       Yours sincerely, 
                                                                                                                                        Jiao

**Comment by polettif** [comment]
As I said in the [original thread](https://github.com/matsim-org/matsim-code-examples/issues/302): The recommended way to create a schedule I by converting a existing schedule provided  a public transit agency. Schedules are usually available as [GTFS feeds](https://gtfs.org/reference/static/) and can be converted with [pt2matsim's gtfs converter](https://github.com/matsim-org/pt2matsim/wiki/Creating-an-unmapped-MATSim-transit-schedule#from-gtfs). If you don't have schedule data available, you need to create your own schedule, either in GTFS or in MATSim's format.

In any case, especially if you want to create your own schedule by hand, you should read chapter 16 (Modeling Public Transport with MATSim) in the [MATSim book](http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf).

**Comment by polyuliguoy** [comment]
Hello, Jiao. Would you give some experience about transit network creation using shapefiles? Thank you.
