### ISSUE TITLE
PublicTransitMapper stopped

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/pt2matsim#103]
Dear all:
        I'm using PublicTransitMapper to matching my "unmapped" public transport schedule file to the network file. When I run the main class, it didn't continue when calculating the 153th lines:
![image](https://user-images.githubusercontent.com/35290093/79871210-9d371080-8416-11ea-9b8a-deaeb48737c7.png)
       Could anyone can help me. 
       Hope to get your early reply soon.

**Comment by sebhoerl** [comment]
Could it be that you didn't give enough of memory to the process? (`-Xmx` flag in Java)

**Comment by jiao1997** [comment]
> Could it be that you didn't give enough of memory to the process? (`-Xmx` flag in Java)

Hi， I have set -Xmx to 1600m which is the max memory I can set. But it didn't work

**Comment by sebhoerl** [comment]
This would be 1.6GB of memory, I doubt that this is your maximum. Otherwise you obviously need a better machine ;)

**Comment by jiao1997** [comment]
> This would be 1.6GB of memory, I doubt that this is your maximum. Otherwise you obviously need a better machine ;)

When I tried to increase -Xmx to 2000m, errors occurred:
![image](https://user-images.githubusercontent.com/35290093/80205033-8aae1880-865c-11ea-9a8d-a6730e60f0ba.png)

**Comment by sebhoerl** [comment]
Is this on linux? What goes `free -g` give?

**Comment by jiao1997** [comment]
> Is this on linux? What goes `free -g` give?

It's on windows

**Comment by jiao1997** [comment]
> Is this on linux? What goes `free -g` give?

Hi friend, I have test my max memory :
![image](https://user-images.githubusercontent.com/35290093/80213246-77ef1000-866b-11ea-82cd-15542a541cc7.png)
It seems that 10g is available, but I can't set  bigger than 1600m in IDEA

**Comment by sebhoerl** [comment]
This seems to be an old issue and not really related to pt2matsim? Please re-open if there are further questions.
