### ISSUE TITLE
Unsure if functionality "vehicle working" already exists for transit vehicles

### ISSUE THREAD

**Issue by Marbventa** [matsim-org/pt2matsim#105]
Hi,

i am currently unsure if the functionality 'vehicle working'/circulation/Umlauf is already implemented for Transit Vehicles. 

I have checked most useful .java files in this repository - regardless having someone confirm, that the functionality doesn't already exist would help me loads since I am considering implementing this functionality myself.

Regards
Gero

**Comment by Marbventa** [comment]
Unfortunately i had an error 404 and reposted this 'issue'. Sorry about that.

**Comment by polettif** [comment]
As I'm not quite sure what you mean, I'd say it's not implemented... You probably checked [GtfsConverter](https://github.com/matsim-org/pt2matsim/blob/55bc026302187d8dba90a341e250b7cc6c5ad5d2/src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java#L314) which creates a new vehicle for each departure of a route which then only serves this departure. HafasConverter works similarly. Of course it'd be great if you could implement this!

**Comment by Marbventa** [comment]
Hi, thank you so much for your input. I was also checking the .editor and the .run configs.

I will msg you once I have completed what I am working on.

I will close the issue now! Thanks for your fast response.
