### ISSUE TITLE
Default Config

### ISSUE THREAD

**Issue by Tamson17** [matsim-org/pt2matsim#107]
Dear all:
      I'm using this project to generated file and run the public transport module of matsim. How can I run CreateDefaultOsmConfig, or this project need my own Osm file?
      Hope to get your early reply soon.

**Comment by polettif** [comment]
You run the java class `CreateDefaultOsmConfig` with the output path as first argument ([see wiki entry](https://github.com/matsim-org/pt2matsim/wiki/Creating-a-multimodal-network-(Osm2MultimodalNetwork))) either in a Java IDE (Eclipse or IntelliJ Idea) or via terminal. Yes you do need your "own" osm file, i.e. you need to download an osm-xml-file (from openstreetmap or geofabrik)

Note that CreateDefaultOsmConfig only gives you a config xml file. You'll have to edit it, most importantly add the path to your osm file, before it'll work with Osm2MultimodalNetwork.

**Comment by Tamson17** [comment]
Thanks for your reply！
And I just tried to run PT2MATsimExample, I found that it also need a hafas file too? 
When the code run to "new File(pathToHafasFolder, ECKDATEN).exists()", it threw out an error that "ECKDATEN does not exist", so I had this question.

**Comment by Tamson17** [comment]
Thanks for your reply!
I will read the guide carefully and successfully run the code.

**Comment by Tamson17** [comment]
I just converted my own osm file, and find that something wrong with the shape, maybe I got the coordinate system wrong？

**Comment by polettif** [comment]
Sounds like it but that's hard to tell without further info. You should convert the network to a [projected coordinate system](https://github.com/matsim-org/pt2matsim/wiki/Mapping-a-MATSim-schedule-to-a-MATSim-network-(Public-Transit-Mapper)#coordinate-systems) using the right EPSG code.

**Comment by Tamson17** [comment]
Thank you for your reply!
I'll confirm that as soon as possible.

**Comment by sebhoerl** [comment]
This seems to be solved? Please re-open if not.
