### ISSUE TITLE
Long stationary queues of pt vehicles

### ISSUE THREAD

**Issue by alexanderbachev** [matsim-org/pt2matsim#113]
Dear guys,

I've used the pt2matsim to generate a multimodal network from OSM, convert a (self-made) GTFS feed to transitSchedule and default transitVehicles files and then mapped the schedule. It all seems fine, with not too many PlausibilityWarnings. When running a pt scenario simulation, I've noticed that the pt vehicles line up on some streets and form long queues which either move extremely slowly or don't move at all (at the end of a line). (see screenshot) In the particular case this phenomenon happens with only pt vehicles circulating on the network, so the network should not be overloaded with cars and be congestions. I investigated the mapped schedule file and found out that for every trip on a transit line a new pt vehicle is generated which enters the network at the designated departure time. Is that the current practice in the field or is it due to a low quality GTFS feed?

My second question is what happens to a pt vehicle after it completes its trip? Is it removed from the network and if not, does it block other vehicles by staying at the last stop of its route until the end of the simulation? Thanks

<img width="1552" alt="Screenshot 2020-06-09 at 15 17 17" src="https://user-images.githubusercontent.com/63676508/84148088-20640280-aa67-11ea-992b-716fef1eccbb.png">

**Comment by polettif** [comment]
> I investigated the mapped schedule file and found out that for every trip on a transit line a new pt vehicle is generated which enters the network at the designated departure time. Is that the current practice in the field or is it due to a low quality GTFS feed?

It's not a problem with the feed, this works as intended. Creating a new vehicle for each trip (transitRoute in MATSim) is a simplified assumption since GTFS feeds normally don't contain any info on vehicle usage (see #105).

Now, I cant' really tell why your vehicles don't move on to the next link. I did encounter some problems in the past with very low link freespeeds which made it basically impossible to move through them. What does the network file for these links look like?

> My second question is what happens to a pt vehicle after it completes its trip? Is it removed from the network and if not, does it block other vehicles by staying at the last stop of its route until the end of the simulation?
AFAIK it's removed from the network but I'm not really up to date on how pt is implemented in MATSim.

**Comment by alexanderbachev** [comment]
@polettif thank you, for the fast reply!
>Creating a new vehicle for each trip (transitRoute in MATSim) is a simplified assumption since GTFS feeds normally don't contain any info on vehicle usage.

This is logical indeed. Do you have any idea what happens to each pt vehicle after it completes its trip. My assumption is that it stays at the last stop of the trip. That's the only way I can explain the accumulation of stationary pt-vehicles at the end stop of the route. This phenomenon is present at many places on the map. 

> Now, I cant' really tell why your vehicles don't move on to the next link. I did encounter some problems in the past with very low link freespeeds which made it basically impossible to move through them. What does the network file for these links look like?

Please see the 2 screenshots of that region of the map portraying the capacity and free speed of the network. I have the flowCapacityFactor and storageCapacityFactor set to 0.01, as I am simulating with 1 pct of the population. I have to increase the free speeds a bit, because they don't represent the reality. However, to me it doesn't seem like they are too low to prevent vehicles from passing. I'll attach the configuration files I've used for network generation and mapping, in case they are needed.

<img width="1498" alt="Screenshot 2020-06-14 at 0 02 26" src="https://user-images.githubusercontent.com/63676508/84579058-6b697700-add3-11ea-9904-6e76631e051b.png">
<img width="1498" alt="Screenshot 2020-06-14 at 0 07 39" src="https://user-images.githubusercontent.com/63676508/84579060-6d333a80-add3-11ea-929b-a93087e8e6ca.png">

[Archive.zip](https://github.com/matsim-org/pt2matsim/files/4775466/Archive.zip)

**Comment by polettif** [comment]
> This is logical indeed. Do you have any idea what happens to each pt vehicle after it completes its trip. My assumption is that it stays at the last stop of the trip. That's the only way I can explain the accumulation of stationary pt-vehicles at the end stop of the route. This phenomenon is present at many places on the map.

Unfortunately, I don't know what exactly happens in the simulation.

> I have to increase the free speeds a bit, because they don't represent the reality. However, to me it doesn't seem like they are too low to prevent vehicles from passing. I'll attach the configuration files I've used for network generation and mapping, in case they are needed.

It's possible that the link capacity is so low that pt vehicles can't move on to the next link. Does this issue come up without adjusted flow- and storageCapacityFactor? However, I'm afraid I can't really help you further with this issue, you might get better answers on [matsim-code-examples](https://github.com/matsim-org/matsim-code-examples/issues?q=is:issue).

**Comment by alexanderbachev** [comment]
>Does this issue come up without adjusted flow- and storageCapacityFactor?

I haven't thought about it. I will try it out. Thank you for your input!

**Comment by sebhoerl** [comment]
This seems to be solved? Please re-open if not.
