### ISSUE TITLE
add extended route type 907

### ISSUE THREAD

**Issue by mrieser** [matsim-org/pt2matsim#115]
The latest GTFS data from Switzerland (e.g. https://opentransportdata.swiss/de/dataset/6f55f96d-7644-4901-b927-e9cf05a8c7f0/resource/308f9e55-9d2e-493c-90cc-f492fef8dde4/download/gtfsfp20202020-03-04.zip) contains routes with type 907:

```txt
"61-110-Y-j20-1","293","110-Y","","Drahtseilbahn","907"
"61-111-Y-j20-1","236","111-Y","","Drahtseilbahn","907"
"61-112-Y-j20-1","219","112-Y","","Drahtseilbahn","907"
"61-113-Y-j20-1","219","113-Y","","Drahtseilbahn","907"
```

This currently leads to an exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid GTFS route type: 907
	at org.matsim.pt2matsim.gtfs.lib.GtfsDefinitions$ExtendedRouteType.getExtendedRouteType(GtfsDefinitions.java:393)
	at org.matsim.pt2matsim.gtfs.lib.GtfsDefinitions$RouteType.getExtendedRouteType(GtfsDefinitions.java:212)
	at org.matsim.pt2matsim.gtfs.GtfsFeedImpl.loadRoutes(GtfsFeedImpl.java:395)
	at org.matsim.pt2matsim.gtfs.GtfsFeedImpl.loadFiles(GtfsFeedImpl.java:149)
	at org.matsim.pt2matsim.gtfs.GtfsFeedImpl.<init>(GtfsFeedImpl.java:84)
```

Sadly, this exception is then not caught, which results in the conversion to not complete.
The code in [GtfsFeedImpl](https://github.com/matsim-org/pt2matsim/blob/43d0f1e175779fd588bb26db1babb417c5260190/src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java#L397) seems to expect a `null` value when a route type is not found and then handles this more gracefully by just ignoring this route. Too bad `null` is never returned, but an exception instead.
Not sure what the design decision on this point is, but I would prefer if the conversion would continue with some kind of warning. 

For the time being, I'll likely going to replace the `"907"` with `"1400"` (Standseilbahn) in my gtfs-data.

**Comment by polettif** [comment]
Yes, an exception is not very elegant. I guess there's two parts to this: 
- `GtfsImpl`: Reading unknown route types with a warning should be fine, especially since extended route type are a pretty loose standard anyways. I think we should scrap the idea of "ignored routes" in `GtfsImpl` altogether and let the converter handle them.
- `GtfsConverter` Unknown route types are given a default vehicle (OTHER) and a warning is already being logged, no need to change there.
