### ISSUE TITLE
Errors when creating unmapped transit schedule

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/pt2matsim#117]
Hello everyone,

I am new to MATSim and currently building my first scenario. Since I don't know how to obtain a suitable public transport input, I was guided here.

I am modelling the public transport network in Brussels, and I have downloaded the latest GTFS file. According to the guidance, the first step should be creating an unmapped MATSim transit schedule, that's the place where my error occurred.

Basically, I am using IDEA with the below argument:
`E:\Model\Mobility\PublicTransportBrussels\gtfs "dayWithMostServices" EPSG:32631 E:\Model\Mobility\PublicTransportBrussels\transitSchedule E:\Model\Mobility\PublicTransportBrussels\vehicleFile`

The first insertion is the root folder of my GTFS file after unzipped, I decided to use the dayWithMostServices option and EPSG:32631 coordinate system (the same one with my network). The last two insertions are just two new folders I created for the output.

The exception I encountered after run is as the image below:
![image](https://user-images.githubusercontent.com/63421908/87438138-76404300-c5ef-11ea-97b8-fa647945ab3e.png)

To further clarify, I created a new project for this pt2matsim pipeline (instead of adding code in the original MATSim pom.xml), what I did is just clone the URL of this project and generating the pipeline from the visual control (that may be the potential reason for this? Since it lacks of MATSim package? It's just my personal guessing)

I’m wondering if anyone is aware of the potential reason for this exception? Thanks very much for your help in advance! :)

**Comment by sebhoerl** [comment]
First, the two last arguments in your command should be paths to *files*, not to *directories*, e.g. `path/to/transit_schedule.xml.gz`.

Second, this looks more like a dependency problem. Did you import the cloned repository properly as a Maven project into IDEA? Can you run a Maven update to pull all the dependencies?

**Comment by jingjunL** [comment]
> First, the two last arguments in your command should be paths to _files_, not to _directories_, e.g. `path/to/transit_schedule.xml.gz`.
> 
> Second, this looks more like a dependency problem. Did you import the cloned repository properly as a Maven project into IDEA? Can you run a Maven update to pull all the dependencies?

Hi Dr Hörl,

Thanks for your reply! Indeed, I changed the two last arguments and added below code in my pom file (which is weird because originally it's not there), magically it works and I obtained my transit Schedule and vehicle file :)

```
<repositories>
    <repository>
        <id>pt2matsim</id>
        <url>http://dl.bintray.com/polettif/matsim</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>org.matsim</groupId>
        <artifactId>pt2matsim</artifactId>
        <version>20.5</version>
    </dependency>
</dependencies>
```

Cheers,
Jingjun

**Comment by Areza622** [comment]
> First, the two last arguments in your command should be paths to _files_, not to _directories_, e.g. `path/to/transit_schedule.xml.gz`.
> 
> Second, this looks more like a dependency problem. Did you import the cloned repository properly as a Maven project into IDEA? Can you run a Maven update to pull all the dependencies?
Dear Dr Hörl, what is the way/code to specify input or output path to multiple arguments in a class? Would you please give an example in Osm2TransitSchedule?
Thank you in advance.
