### ISSUE TITLE
calendar_dates.txt as a valid alternative to calendar.txt

### ISSUE THREAD

**Issue by gharaviSara** [matsim-org/pt2matsim#121]
Dear Developers,
I am trying to generate transit schedule for Quebec City RTC ,as I check with several sources ,
https://transitfeeds.com/p/reseau-de-transport-de-la-capitale/40 
https://www.rtcquebec.ca/donnees-ouvertes

The calendar.txt does not exist in GTFS folder,so now the question is why pt2matsim not recognizing this calendar_dates.txt as a valid alternative to calendar.txt, is there any tricks that I manually change in my pt2matsim files to accept calendar_dates.txt ?
Best,
Sarah

**Comment by sebhoerl** [comment]
I'm not sure, if this is covered in pt2matsim so far, @polettif ? So far I have also never seen a GTFS without the calendar.txt, but according to the specification it seems to be valid (option 2 at https://developers.google.com/transit/gtfs/reference#calendar_datestxt )

So one option would be that you implement this functionality (or check if it is there). Another alternative would be to generate a `calendar.txt` such that it encodes the information that is now in `calendar_dates.txt`. As far as I understand this would mean creating the service ID's there and specifying the correct week day (as defined now in the `calendar_dates.txt`) and then using `calendar_dates.txt` to define that each service really only exists on their specified day. Does it make sense?

**Comment by gharaviSara** [comment]
Dear Sebastian,
Many thanks for your kind reply, you are right base on calendar_date.txt I
figure out the weekly plan (seven digit 0,1)of transit is inside the
service id (e.g.20202015multint-00011000) and the end and start dates were
present in feed_info.txt) so I easily create the calendar.txt, but in
another city even I do not have this weekly digit, see link
<https://transitfeeds.com/p/societe-de-transport-de-levis/1173/latest/file/calendar_dates.txt>,
so do you think I can assume it as regular weekly basis ?
Cheers,
Sara

**Comment by polettif** [comment]
pt2matsim should be able to handle feeds without calendar.txt (#101): Every date encountered in calendar_dates.txt should be added (or removed) from a service id, regardless of start and end dates in calendar.txt. So I'm not sure what the issue is exactly. Can you post an reproducible example with the latest version of pt2matsim?

**Comment by gharaviSara** [comment]
Dear Polettif,
as I understand correctly,I use pt2matsim version ,**v19.5**  which return error of missing calendar.txt ,about the example of calendar_date.txt that I have is like below,

﻿service_id,date,exception_type
47320,20200615,1
47320,20200616,1
...

Without any start_date , end_date  and days of the week ,

Could you kindly say in which version accept calendar_date.txt ? or which part should be edited to pass this missing calendar.txt error?

**Comment by polettif** [comment]
I'd strongly suggest using the latest release version **20.7**. Though the issue has been fixed since 19.11 in the aforementioned pull request.

**Comment by gharaviSara** [comment]
I tried before to use 20.7 version but when installing , I face this error :
Executing Java:
  java -cp /home/sara/Data/temp/matsim.java.pt2matsim_cache/pt2matsim/target/pt2matsim-19.5-shaded.jar -Xmx10G org.matsim.pt2matsim.run.CreateDefaultOsmConfig test_config.xml
Error: Could not find or load main class org.matsim.pt2matsim.run.CreateDefaultOsmConfig
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    config = config)
  File "/home/sara/matsim_quebec_province/pipeline.py", line 243, in run
    data = stages[stage_name].execute(context)
  File "/home/sara/matsim_quebec_province/matsim/java/pt2matsim.py", line 27, in execute
    java(jar, "org.matsim.pt2matsim.run.CreateDefaultOsmConfig", ["test_config.xml"], cwd = context.cache_path)
  File "/home/sara/matsim_quebec_province/utils/java.py", line 27, in __call__
    return sp.check_call(command_line, cwd = cwd)
  File "/home/sara/anaconda3/envs/test/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-cp', '/home/sara/Data/temp/matsim.java.pt2matsim_cache/pt2matsim/target/pt2matsim-19.5-shaded.jar', '-Xmx10G', 'org.matsim.pt2matsim.run.CreateDefaultOsmConfig', 'test_config.xml']' returned non-zero exit status 1.

thats why we switch to older version to pass this shaded.jar error.

**Comment by gharaviSara** [comment]
Perfect! Thanks. It works
