### ISSUE TITLE
Some links with freespeed="Infinity"

### ISSUE THREAD

**Issue by AHolliday** [matsim-org/pt2matsim#126]
I used pt2matsim 19.4 to generate matsim files for the transit system of the city of Laval in Quebec.  Inspecting the final_network.xml file, however, I find that a number of the links have freespeed set to "Infinity".  This does not occur in final_car_network.xml.  Can someone explain why pt2matsim adds these "instantaneous" links to my network?

**Comment by polettif** [comment]
This usually happens if two subsequent public transit stops have the same departure time. So infinity speed is necessary to ensure that the pt vehicle travelling on the link reaches the next stop instantly. Hard to tell without an example though.

**Comment by polettif** [comment]
I had a look at the feed and there are several stop pairs with the same departure time. For example the second and third stop in trip `MARS2012E2S10915210017` (see below). In fact 79 gtfs routes (TransitLines in MATSim) do have stop pairs with no time offset. 

Here's the R script I used (can't really peek into GTFS with Java):
``` r
library(tidytransit)
library(dplyr)

g = read_gtfs("laval-gtfs.zip") %>% set_hms_times()

st = g$stop_times %>%
    arrange(trip_id, stop_sequence) %>%
    group_by(trip_id) %>%
    mutate(dep_delta = c(NA, diff(departure_time_hms))) %>%
    ungroup()

st %>%
    select(trip_id, departure_time, stop_sequence, stop_id, dep_delta)
#> # A tibble: 210,627 x 5
#>    trip_id                departure_time stop_sequence stop_id       dep_delta
#>    <chr>                  <chr>                  <int> <chr>             <dbl>
#>  1 MARS2012E2S10915210017 15:15:00                   1 MARS20CP47012        NA
#>  2 MARS2012E2S10915210017 15:17:00                   2 MARS2041241         120
#>  3 MARS2012E2S10915210017 15:17:00                   3 MARS2046417           0
#>  4 MARS2012E2S10915210017 15:20:00                   4 MARS20CP49012       180
#>  5 MARS2012E2S10915210317 15:15:00                   1 MARS20CP47012        NA
#>  6 MARS2012E2S10915210317 15:17:00                   2 MARS2041241         120
#>  7 MARS2012E2S10915210317 15:17:00                   3 MARS2046417           0
#>  8 MARS2012E2S10915210317 15:20:00                   4 MARS20CP49012       180
#>  9 MARS2012E2S13021190029 21:13:00                   1 MARS20CP47012        NA
#> 10 MARS2012E2S13021190029 21:15:00                   2 MARS2041241         120
#> # … with 210,617 more rows

# number of routes containing stop pairs with no time offset
st %>%
    filter(dep_delta == 0) %>%
    left_join(g$trips, "trip_id") %>%
    pull(route_id) %>% unique() %>% length()
#> [1] 79
```

**Comment by AHolliday** [comment]
Not sure how my script missed this.  Thanks for looking into it.
