### ISSUE TITLE
Undefinied time caused by faulty transit schedule

### ISSUE THREAD

**Issue by steffenaxer** [matsim-org/pt2matsim#128]
In particular cases, e.g. due to spatial filtering of a gtfs feed, it could happen, that trip.getStopTimes() delivers less than 2 stops.
2 Stops are at least required in order to calculate offsets between stops. Otherwise the resulting schedule will provide a transit route with 1 stop that has no offsets. A stop with no arrival and no departure offset causes a undefinied time exception in matsim13 when using sbb pt router.

Thus we should think on changing this code to:

https://github.com/matsim-org/pt2matsim/blob/master/src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java
Method: createTransitRoute

```
Old:
		if(trip.getStopTimes().size() == 0) {
			noStopTimeTrips++;
			return null;
		}`
New:
		if(trip.getStopTimes().size() >= 2) {
			noStopTimeTrips++;
			return null;
		}`

```

**Comment by polettif** [comment]
Thanks for pointing this out! In general, time exceptions aside, transit routes with only one stop are not that useful in a simulation anyways.

Your solution is the way to go, can you put this in a pull request?
