### ISSUE TITLE
Bintray shut down

### ISSUE THREAD

**Issue by markusstraub** [matsim-org/pt2matsim#143]
Bintray was shut down, so https://bintray.com/polettif/matsim/pt2matsim is no longer reachable. Could you switch over to e.g. https://repo.matsim.org (see https://matsim.org/2021/matsim-13-released/)?

**Comment by mrieser** [comment]
@polettif If you want to use repo.matsim.org, drop me a line so I can create an account for you to push to the repository.

**Comment by polettif** [comment]
> @polettif If you want to use repo.matsim.org, drop me a line so I can create an account for you to push to the repository.

Yes, that'd be the best solution, thanks. I might need some help setting it up, I couldn't get the maven release to work with github actions on bintray (some issue with secret tokens).

**Comment by kensongzhu** [comment]
May I ask how far is the process going?  I am having the problems resolving the dependencies on a new machine.
