### ISSUE TITLE
Typo in Log Message

### ISSUE THREAD

**Issue by gvermillion** [matsim-org/pt2matsim#145]
I noticed a typo in the logs today:

https://github.com/matsim-org/pt2matsim/blob/722542813caf7061708194472171d7c45406d3b7/src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java#L170

The log message should say `"Calculating pseudoTransitRoutes ..."`. 

Best,
Grant

**Comment by polettif** [comment]
Thank you 👍
