### ISSUE TITLE
How to find the closest link from a stop.

### ISSUE THREAD

**Issue by rara1484** [matsim-org/pt2matsim#146]
Hi.
I am planning to create a multimodal network for Tokyo using pt2matsim.

I was able to create the Tokyo network (including the trains).

The problem is that I don't know which link the train stops correspond to.

There is no gtfs data available for everyone in Tokyo, so I have to create my own transit schedule.
When I create a transit schedule, I have to include the link that corresponds to the stop.
Therefore, it is necessary to know the link that the stop corresponds to.

The solution I have in mind is to use JOSM to find the link closest to the train stop, but the number of stations is so large that it would be a tremendous task.

So what I want to ask is: "Can I have it pick the closest link from the coordinate data of the stops?　".

I do have the network and the coordinate data of the stops.
If anyone knows how to solve this problem, please let me know.

Translated with www.DeepL.com/Translator (free version)

**Comment by mrieser** [comment]
double posting, see https://github.com/matsim-org/matsim-code-examples/issues/580 .
