### ISSUE TITLE
Issue with artificial links generated

### ISSUE THREAD

**Issue by federicobigi** [matsim-org/pt2matsim#147]
Hello, 
I'm using pt2matsim. I'll try to explain myself as clear as possible.
I downloaded first the .osm map, and using the MATSim plugin in JOSM I generated the network.xml. After that, I downloaded the GTFS files, executed first the GTFS2Transit to generate both the transit and the vehicles, then I generated the config file with CreateDefaultPtMapperConfig, modified it accordingly in order to generate the final network.
When I finally run the checkmappedscheduleplausability, I saw that the mapper generated around 10k artificial links, even though in the plausability output it could find out the corrected transit route (schedule_TransitRoutes).
I'll attach the zip of the plausability and the config file, maybe I messed up in the generation of the config file.
Kind regards,

Federico Bigi
[allPlausibilityWarnings.xlsx](https://github.com/matsim-org/pt2matsim/files/6671695/allPlausibilityWarnings.xlsx)
[config.txt](https://github.com/matsim-org/pt2matsim/files/6671705/config.txt)

**Comment by federicobigi** [comment]
Also, I'd like to attach this picture: the circles appears to be the artificial links generated for public transport in general
![image](https://user-images.githubusercontent.com/84392852/122525726-d1f22800-d019-11eb-8387-7064024bb687.png)

**Comment by polettif** [comment]
Looks to me like an issue with coordinate systems, [there's a note on that in the wiki](https://github.com/matsim-org/pt2matsim/wiki/Mapping-a-MATSim-schedule-to-a-MATSim-network-(Public-Transit-Mapper)#coordinate-systems). Did you convert the schedule to a projected coordinate system?

**Comment by federicobigi** [comment]
Hi,
from the wiki, _"It's best to look up the EPSG code of a coordinate system that covers your area of interest and use it as a parameter for the network and schedule conversion."_. You mean that, given the osm file and the GTFS files, once I go into the GTF2TransitSchedule, instead of setting WGS84 as the third argument I have to put a code of the interested area? Sorry I'm not so practical with topography and transformations.
Kind regards,

Federico

**Comment by federicobigi** [comment]
Goodmorning, 
I tried as you mentioned. I initially created the map on JOSM, but today I used your tool (CreateDefaultOsmConfig and then, setting inside the parameters, Osm2MultimodalNetwork) to translate the map using a different EPGS code (EPSG:2169). Then, the I translated the GTFS files as well using the GTF2TransitSchedule using the same code as before. Now, I obtained 1k artificial link. Do you think this number of link is the average or am I still missing something?
Kind regards,

Federico

**Comment by polettif** [comment]
Yes the workflow looks like this:
```
GTFS (WGS84) -> GtfsTransitSchedule -> MATSim schedule (EPSG:*)  \
                                                                  PTMapper
OSM (WGS84) -> Osm2MultimodalNetwork -> MATSim network (EPSG:*)  /  
```
both Gtfs2TransitSchedule and Osm2Multimodalnetwork should convert their input data to a projected coordinate system.

I can't tell whether 1k link is ok for your area but it does seem high. It's generally better to just look at the generated network/schedule (in via) and see if the links make sense or if some parts are missing (e.g. railway). I'd focus on that visual analysis first instead of the plausibility check.
