### ISSUE TITLE
Too much links and nodes

### ISSUE THREAD

**Issue by captainnemo2005** [matsim-org/pt2matsim#151]
Hi, I try to use pt2matsim to generate a network using pt2matsim. 
I use the data from https://download.geofabrik.de/australia-oceania.html and cut it with .poly generate from http://polygons.openstreetmap.fr/?id=4246124 for Melbourne city using osmosis to get the osm file. 
After running the WorkFlow in pt2matsim with basics config I obtain the network but it contains too many links and nodes.

This is how it looks in Via. How can I reduce the number of links and nodes so that the network can be used for simulation?
Currently, the network has 236420 nodes and 508199 links and I wish to have around 30000 nodes and 60000 links.

Thanks a lot for the amazing work.
<img width="970" alt="Screen Shot 2021-07-20 at 6 58 48 pm" src="https://user-images.githubusercontent.com/36758759/126293392-a86da8bd-37d7-4323-af77-d184fc7657a8.png">

**Comment by JWJoubert** [comment]
Hi @captainnemo2005, I typically filter the _OpenStreetMap_ file, using `osmosis`, *_before_* running it through `pt2matsim`. For example, after you clipped with the polygon, filter on specific highway types:
```
osmosis --read-pbf file="input_osm.pbf" --tf accept-ways highway=motorway,motorway_link,trunk,trunk_link,primary,primary_link,secondary,secondary_link completeWays=yes --un --write-pbf file="output_osm.pbf"
```

**Comment by captainnemo2005** [comment]
Thanks for your prompt advice  @JWJoubert. I applied the exact comment and receive this error:
Exception in thread "main" java.lang.RuntimeException: No ways available in osm file
Can you recommend what link I should filter for network with car, pt, tram, truck and walk mode?

This comment seem to eliminate all links:
highway=motorway,motorway_link,trunk,trunk_link,primary,primary_link,secondary,secondary_link

Besides, I also receive a 100mb transitschedule.xml file. How should I scale down this file if said I use 25% of the city population?

Thanks so much for your time.

**Comment by JWJoubert** [comment]
I cannot comment on what is _right_ for your scenario, sorry.

> This comment seem to eliminate all links:

that comment is preceded by `accept-ways`, which means those are the ones that should remain. Are you using `osmosis` on the command line for this? If so, write the output to a readable xml, replacing
```
--write-pbf file="output_osm.pbf"
```
with
```
--write-xml file="output_osm.osm"
``
and check what remains in that file. My original point was just this: you can do the filtering _outside_ of `pt2matsim`. I am not sure how you would do it _inside_ the `pt2matsim` environment.

**Comment by captainnemo2005** [comment]
Thanks for this advice @JWJoubert, the overall number of links was reduced but the network looks not so well connected. Do we have any way to check the connectivity of the network or at least know the network can be used for simulation in the later steps?

In the picture below, the red link looks like they are transit links and got broken down and not connected anymore. 
<img width="1069" alt="Screen Shot 2021-07-21 at 11 49 42 am" src="https://user-images.githubusercontent.com/36758759/126418280-51559ce5-8355-47a0-a751-dc207684939e.png">


This is the comment I used to filter the links: 

osmosis --read-xml file=mel.osm --tf accept-ways highway=motorway,trunk,primary,secondary --used-node --write-xml file=output2.osm

**Comment by JWJoubert** [comment]
> ... but the network looks not so well connected.

I agree @captainnemo2005. There is a `NetworkCleaner` in the MATSim infrastructure, but I do not think `pt2matsim` uses it for public transport. As far as I know, it is a config setting on the `pt2matsim` side... you actually **_don't_** want **_only a fully_** connected network, because dedicated rail does not share infrastructure with the road, so only the larger cluster (road) will then remain.

I wish I had a solution for you, but alas, I don't... I have similar issues that I have not been able to resolve (yet) (See issue #148). I am trying to sort it out by fixing it on the _OpenStreetMap_ side. So, if this portion of your question is now solved, maybe close this issue and we keep the other one open.
