### ISSUE TITLE
About create multimodal network from combined GTFS file. 

### ISSUE THREAD

**Issue by fayexin** [matsim-org/pt2matsim#154]
Hi, 

I am creating combined GTFS file with two GTFS file. I could create the networks seperately by each of them. But when I merged them together, the network only created based on one major GTFS file. The schedule also only contains stops from this GTFS file. I am confused why this problem occurs. Thanks!

**Comment by sebhoerl** [comment]
I guess this depends on how you merged them, this is not functionality of pt2mtasim. What tool did you use to do that? Did you verify whether the resulting merged GTFS feed is valid?

**Comment by fayexin** [comment]
I use python code to do the zip file merge through GTFSMerger:

```

from gtfsmerger import GTFSMerger
import zipfile
import pandas as pd

n = GTFSMerger()
f_1 = open('../input/GTFS/gtfs_1.zip', 'rb').read()
f_2 = open('../input/GTFS/gtfs_2.zip', 'rb').read()
n.merge_from_bytes_list([f_1,f_2])

n.get_zipfile("../input/GTFS/gtfs_merged.zip")
with zipfile.ZipFile("../input/GTFS/gtfs_merged.zip", 'r') as zip_ref:
    zip_ref.extractall("../input/GTFS/gtfs_merged/" )

data = pd.read_csv("../input/GTFS/gtfs_merged/calendar.txt")
data["end_date"] = data["end_date"].str.replace("-","")
data["start_date"] = data["start_date"].str.replace("-","")
data.to_csv("../input/GTFS/gtfs_merged/calendar.txt")

data = pd.read_csv("../input/GTFS/gtfs_merged/calendar_dates.txt" )
data["date"] = data["date"].str.replace("-","")
data.to_csv("../input/GTFS/gtfs_merged/calendar_dates.txt" )

data = pd.read_csv("../input/GTFS/gtfs_merged/transfers.txt")
data["min_transfer_time"] = data["min_transfer_time"].astype(str).str.replace(".0","")
data.to_csv("../input/GTFS/gtfs_merged_transfers.txt")
```


How could I verify the merged GTFS file is valid?

Thanks a lot!

**Comment by sebhoerl** [comment]
If you open the txt files, do you find the information that you have in the other files? You could just take a line of each file and check if you find it in the other files maybe. And first make sure that none of the files is empty (for departures etc.). Otherwise, maybe it is an issue with the timing? When you use pt2matsim, do you define a specific day or do you let pt2matsim let choose the day with most services? Maybe in the former case, something is wrong with the formatting of the dates?

**Comment by fayexin** [comment]
I think it caused by the date problem. I make all of them consistent and from same year and it works! 
Thanks a lot.
