### ISSUE TITLE
Creating Multimodal network by other schedule and vehicle file

### ISSUE THREAD

**Issue by fayexin** [matsim-org/pt2matsim#155]
Dear sir, 

I want to create a multimodal network using the schedule and vehicle file I made from another source. Is there any way that I could create that network?

Thanks!

**Comment by polettif** [comment]
It's not possible to create a multimodal network (i.e. a full MATSim network including car links) just from the schedule and vehicle file alone. There's not enough network information contained in those files.

**Comment by fayexin** [comment]
Can I use the the schedule and vehicle file I made from another source together with the corresponding  OSM file to get a multimodal network?

**Comment by polettif** [comment]
> Can I use the the schedule and vehicle file I made from another source together with the corresponding OSM file to get a multimodal network?

Yes. Just convert the network from OSM with `Osm2MultimodalNetwork`. You can then also map the existing schedule to the newly created network.
