### ISSUE TITLE
GTFStransfer problem

### ISSUE THREAD

**Issue by china-shuai** [matsim-org/pt2matsim#157]
Hello, When I run gtfs2transitschedule, I find that the generated arrivaloffset and departureoffset are equal. That is, there is no waiting time in the middle of the arrival and departure times. Is this an error that would pose a simulation problem?

**Comment by polettif** [comment]
A lot of GTFS data has no time between arrival/departure so converted MATSim schedules also don't, AFAIK this has not lead to problems with the simulation.
