### ISSUE TITLE
Creating OSM Network with Shapefile in pt2matsim

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/pt2matsim#160]
Hello everyone,

We are trying to generate a MATSim scenario for our city. We have already generated our plan.xml so the next step would be generating our network and pt.

The only available OSM network we can download from http://download.geofabrik.de/ is national wide, but our scenario is on the city level. I have a shapefile for our city and I know in MATSim we can filter the OSM with the shapefile (like this in matsim code example: https://github.com/matsim-org/matsim-code-examples/blob/13.x/src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java). However, I don't know if I can define this in pt2matsim. Or, if I adapted this code based on my scenario, the only available mode in the network would be car and bike, will that be enough if I directly import the output into the `org.matsim.pt2matsim.run.PublicTransitMapper`? 

Sorry if my question is naive, thank you!

**Comment by JWJoubert** [comment]
Hi @CianGraham, we too use geofabrik as the starting point. Computationally, I find it easier to first **_cut_** the country OSM data to the city level using [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format). I created my city polygons (once-off) using one of the QGIS export formats. The clipping is then a simple terminal command like

```
path/to/bin/osmosis --read-pbf file="./country.osm.pbf" --bounding-polygon file="path/to/city.poly" completeWays=yes completeRelations=yes --write-pbf file="city.osm.pbf"
```

I hope that helps?

**Comment by CianGraham** [comment]
> Hi @CianGraham, we too use geofabrik as the starting point. Computationally, I find it easier to first **_cut_** the country OSM data to the city level using [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format). I created my city polygons (once-off) using one of the QGIS export formats (it requires some manual editing but, as I say, it is once-off). You should then have your city polygon file as `city.poly`. The clipping is then a simple terminal command like
> 
> ```
> path/to/bin/osmosis --read-pbf file="./country.osm.pbf" --bounding-polygon file="path/to/city.poly" completeWays=yes completeRelations=yes --write-pbf file="city.osm.pbf"
> ```
> 
> I hope that helps?

Hi @JWJoubert , thanks for the reply. I am not familiar with qGIS so I am not sure if I follow you correctly. However, in the code example I attached, it takes all links which are motorway, truck and primary street even though they are not within the boundary of provided shapefile (Line 56 to 60). I am wondering if your algorithm also does this?

**Comment by JWJoubert** [comment]
>  it takes all links which are motorway, truck and primary street even though they are not within the boundary of provided shapefile

Yes, it is a result of the `completeWays=yes completeRelations=yes` arguments.

**Comment by JWJoubert** [comment]
I typically do not worry about them too much.

**Comment by JWJoubert** [comment]
🤣  Sorry, @CianGraham, `.poly` is not a formal file extension, it is just MY file extension... it is simply a text file in a specific format, hence my hyperlink to the `osmosis` _standard_.

The idea is just to get the `lon` and `lat` coordinates out of the shapefile. So something like a CSV. I had to read up a bit because I have not done this in a while. The easiest way is to install the (free) QGIS plugin called `mmqgis`, see [here](https://plugins.qgis.org/plugins/mmqgis/). Once installed, it adds a menu item called `MMQGIS`. Click on it and select `Import / Export` -> `Geometry export to CSV file`.

That will give you coordinates. You will then just need to remove the columns you don't want, and add the necessary start and end line attributes to conform to the [osmosis file standard](https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format).

Amn alternative is explained [here](https://newbedev.com/how-to-export-polygon-coordinates-to-csv-not-wkt) but that will mean that you need to do a find-and-replace of all commas with the `\n` in a text editor. But that too works. Either way, it will require some data wrangling or data gymnastics to just get the polygon in the right format.

**Comment by sebhoerl** [comment]
If you are familiar with Python, you can use the following snippet. Basically, you need a boundary.gpkg or boundary.shp in any format that is understood by geopandas and containing one polygon, then it will spit out the correct poly file:
https://gist.github.com/sebhoerl/9a19135ffeeaede9f0abd4cdfedea3bc

**Comment by JWJoubert** [comment]
Nice! Thanks, @sebhoerl. That means I can do that in R probably too. Will definitely look at it. Always nice to have a cleaner and more automated "one-click" workflow.

**Comment by polettif** [comment]
> Nice! Thanks, @sebhoerl. That means I can do that in R probably too. Will definitely look at it. Always nice to have a cleaner and more automated "one-click" workflow.

Just a sidenote, since you mentioned R, I tried converting/cutting OSM with [osmdata](https://github.com/ropensci/osmdata) in the past but unfortunately the package is not quite suitable for reading/writing xml osm files. Maybe [polyread](https://github.com/agila5/polyread) can be of help for creating a custom `write_poly` function.

**Comment by CianGraham** [comment]
> > path/to/bin/osmosis --read-pbf file="./country.osm.pbf" --bounding-polygon file="path/to/city.poly" completeWays=yes completeRelations=yes --write-pbf file="city.osm.pbf"

Thanks, guys. I used the python code by @sebhoerl and get my `city.osm.pbf`, and then I ran the osmosis code by @JWJoubert . By a quick look on QGis, I can see all roads of my city and the primary roads of areas outside of my city.  :)

Just to make sure, I guess the next thing I need to do is follow the steps in the wiki of `pt2matsim` (creating the multimodal network, map schedule ton network etc.)? There is nothing else I should do with the OSM file anymore if I am correct?

Thanks in advance!

**Comment by CianGraham** [comment]
> > > path/to/bin/osmosis --read-pbf file="./country.osm.pbf" --bounding-polygon file="path/to/city.poly" completeWays=yes completeRelations=yes --write-pbf file="city.osm.pbf"
> 
> Thanks, guys. I used the python code by @sebhoerl and get my `.poly` file for my city, and then I ran the osmosis code by @JWJoubert . By a quick look on QGis, I can see all roads of my city and the primary roads of areas outside of my city. :)

Hey guys, I tried to use the `osm.pbf` file in the java class `Osm2MultiModalNetwork` but got the `XML-FATAL` error as below:

`org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
Exception in thread "main" org.matsim.core.utils.io.UncheckedIOException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:199)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
	at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:84)
	at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.run(Osm2MultimodalNetwork.java:60)
	at org.matsim.pt2matsim.run.Osm2MultimodalNetwork.main(Osm2MultimodalNetwork.java:45)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:978)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:196)
	... 4 more
`

I think it's because I should use an `OSM` file instead of the one with `pbf`? Can you please offer me some hints about how to do this? Thanks :)

**Comment by CianGraham** [comment]
<img width="328" alt="1636107566(1)" src="https://user-images.githubusercontent.com/67740217/140495633-a48e5b17-7373-4899-8cf4-29f5a06de705.png">
 
I found these texts in the MATSim handbook. However, I am wondering if I still need to do the `bigRoads.osm.pbf` (in the second step) operation as @JWJoubert said they are already included after `completeWays=yes completeRelations=yes` argument? Thanks!

**Comment by polettif** [comment]
> I think it's because I should use an `OSM` file instead of the one with `pbf`? Can you please offer me some hints about how to do this? Thanks :)

Yes, you need a osm/xml file for pt2matsim. I think using `--write-xml` should work:
```
path/to/bin/osmosis --read-pbf file="./country.osm.pbf" --bounding-polygon file="path/to/city.poly" completeWays=yes completeRelations=yes --write-xml file="city.osm"
```
[Osmosis examples](https://wiki.openstreetmap.org/wiki/Osmosis/Examples)

**Comment by JWJoubert** [comment]
> ... operation as @JWJoubert said they are already included after completeWays=yes completeRelations=yes argument? Thanks!

I think you misunderstood me, @CianGraham. I tried to explain why you still see some (typically higher-order) roads in your final network that stretch outside of your specified polygon. The step in the MATSim book is required if you do model larger regions.

This workflow is now automated in South Africa (for a number of cities). We "clip" the detailed road network for a city. We then (also) extract the OSM data of only the higher-order roads (as per the MATSim book). We then merge these two OSM files.

The _resulting_ OSM file is then converted into a MATSim network. And here you need to make a choice: using the normal MATSim infrastructure, or using this repository's `pt2matsim`. We use both. When we plan to model public transport in more detail, then we use @polettif's `pt2matsim` and if not, we use the "normal" MATSim network.

**Comment by CianGraham** [comment]
> ...The _resulting_ OSM file is then converted into a MATSim network. And here you need to make a choice: using the normal MATSim infrastructure, or using this repository's `pt2matsim`. We use both. When we plan to model public transport in more detail, then we use @polettif's `pt2matsim` and if not, we use the "normal" MATSim network.

Thanks for the detailed explanation @JWJoubert :) I did misunderstand you as I was asking if the `osmosis` code you provided can achieve the same functionality as this code example (https://github.com/matsim-org/matsim-code-examples/blob/13.x/src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java), which also extracts the primary roads of the outside-city areas. 

So my workflow, for now, is using your code and merging it with the higher-order road as in the MATSim book and putting the resulting `OSM` file into `pt2matsim` as we are also interested in the car-pt interaction in the future.

I will close this issue if there are no further comments from you :) Thanks again
