### ISSUE TITLE
MATSim 14.0-SNAPSHOT branch?

### ISSUE THREAD

**Issue by marecabo** [matsim-org/pt2matsim#163]
Thanks for PT2MATSim, we have been using it for some projects recently and thus updated it to work with MATSim 14.0-SNAPSHOT (https://github.com/matsim-org/pt2matsim/compare/master...marecabo:patch-2?expand=1 and https://github.com/matsim-org/pt2matsim/pull/161). 

As MATSim 14.0 is not yet released, would you mind creating a _pt2matsim-snapshot_ branch to accept PRs for the current MATSim snapshot version, instead of the latest stable version?

**Comment by polettif** [comment]
Thanks for pointing this out, I created the branch [dev/matsim-14-snapshot](https://github.com/matsim-org/pt2matsim/tree/dev/matsim-14-snapshot).

**Comment by marecabo** [comment]
Thanks a lot! 🚀
