### ISSUE TITLE
Add as Maven dependency

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/pt2matsim#17]
I'm trying to add `pt2matsim` to my project jar so that I can include it in some production runs.

It works great from within my local IntelliJ setup if I place the compiled jar in `lib/` and then point my project to it as a dependency, but then I can't package it up inside my own jar. I'm trying to figure out at the moment how to bring it in from my local maven repository, but that's not really straight forward.

Is there a place I can point my maven to so that I can bring `org.matsim.pt2matsim` as a project dependency?

**Comment by polettif** [comment]
Release binaries are available on https://bintray.com/polettif/matsim/pt2matsim
