### ISSUE TITLE
Consider bumping maven-deploy-plugin to 2.8

### ISSUE THREAD

**Issue by marecabo** [matsim-org/pt2matsim#171]
Would you be fine with an upgrade of the `maven-deploy-plugin` to version 2.8 from 2.7 in the `pom.xml`?

Version 2.8 offers two new commandline arguments [`altReleaseDeploymentRepository`](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altReleaseDeploymentRepository) and [`altSnapshotDeploymentRepository`](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altSnapshotDeploymentRepository) which makes deploying custom versions (e.g. snapshots) of pt2matsim a bit easier.

Of course, this does not add anything new to the functioning of pt2matsim, this is why I wanted to ask you before doing a pr.

**Comment by polettif** [comment]
Sure, go ahead. Don't see a reason not to do it.

**Comment by marecabo** [comment]
Cool, and thanks for the invite! I'll update both branches then.
