### ISSUE TITLE
Merge multiple GTFS data

### ISSUE THREAD

**Issue by MrGolden1** [matsim-org/pt2matsim#174]
Hello

I use this site https://gtfs.de/en/feeds/ to get GTFS data. There are multiple feeds for different modes of transport.  
How can I merge them and get a single TransitSchedules.xml?

**Comment by ikaddoura** [comment]
Hi, have a look into the following code in our existing case studies:

https://github.com/matsim-scenarios/matsim-metropole-ruhr/blob/8808d23f7bc684d428dbc632b1f29d841f66647b/src/main/java/org/matsim/prepare/CreateSupply.java#L270

https://github.com/matsim-scenarios/matsim-los-angeles/blob/v1.1/src/main/java/org/matsim/prepare/MergeTransitFiles.java

**Comment by MrGolden1** [comment]
@ikaddoura Thanks, It was helpful 🙏
