### ISSUE TITLE
When I run the program I get an error

### ISSUE THREAD

**Issue by Areza622** [matsim-org/pt2matsim#175]
Hello. When I try runnig this app I get the error below:
Exception in thread "main" java.lang.IllegalArgumentException: Config file name as argument needed
	at org.matsim.pt2matsim.run.CreateDefaultOsmConfig.main(CreateDefaultOsmConfig.java:36)

Also I have a general question, I have an .osm file consists of all objects of my desired area and also a zip file for GTFS, I have just cloned this project to Intellij, I tried running according to the following sequence:
Osm2MultimodalNetwork
Osm2TransitSchedule
Gtfs2TransitSchedule
PublicTransitMapper

but unfortunatley I got the mentioned error, is the above sequence correct? would you please tell how should I merge my network .osm file and pulblic transport together using this program?

Thank you in advcance

**Comment by JWJoubert** [comment]
>>>
 Hello. When I try runnig this app I get the error below:
Exception in thread "main" java.lang.IllegalArgumentException: Config file name as argument needed
at org.matsim.pt2matsim.run.CreateDefaultOsmConfig.main(CreateDefaultOsmConfig.java:36)
>>>

The error message seems clear: you need to provide an argument (the config filename that you want to create).

**Comment by Areza622** [comment]
> 

Dear Dr. W. Joubert, thank you for your response. I know my issue seems fundamental, but I just wrote a name for the config file which does not exist yet in CreateDefaultOsmConfig and ran it but got the mentioned error

public static void main(final String[] args) {
		if(args.length < 1) {
			throw new IllegalArgumentException("Config.xml");
		}

is it the part that I should edit?

**Comment by Areza622** [comment]
> > Hello. When I try runnig this app I get the error below:
> > Exception in thread "main" java.lang.IllegalArgumentException: Config file name as argument needed
> > at org.matsim.pt2matsim.run.CreateDefaultOsmConfig.main(CreateDefaultOsmConfig.java:36)
> 
> The error message seems clear, @Areza622: you need to provide an argument (the config filename that you want to create).

Dear Dr. W. Joubert, thank you for your response. I know my issue seems fundamental, but I just wrote a name for the config file which does not exist yet in CreateDefaultOsmConfig and ran it but got the mentioned error

public static void main(final String[] args) {
if(args.length < 1) {
throw new IllegalArgumentException("Config.xml");
}

is it the part that I should edit?

**Comment by JWJoubert** [comment]
No, @Areza622, you do not edit the code. You have to **_pass a config filename_** as an argument. You seem to try and generate and write a config file to disc, yet you do not tell the command line argument what/where that file should be written to.

**Comment by Areza622** [comment]
> Dear Dr. W. Joubert,

Dear Dr. W. Joubert, thank you for your response. In fact my issue is that I dont know how I should specify inout or output address/file name for different arguments. For example in Osm2TransitSchedule there are three arguments 0,1 and 2 but I don't know how should I code their required input file, osm file, and the output files which I don't even know their format.
Thank you for your consideration.

**Comment by Areza622** [comment]
@JWJoubert 
Dear Dr. W. Joubert, thank you for your response. In fact my issue is that I dont know how I should specify inout or output address/file name for different arguments. For example in Osm2TransitSchedule there are three arguments 0,1 and 2 but I don't know how should I code their required input file, osm file, and the output files which I don't even know their format.
Thank you for your consideration.

**Comment by Areza622** [comment]
> No, @Areza622, you do not edit the code. You have to **_pass a config filename_** as an argument. You seem to try and generate and write a config file to disc, yet you do not tell the command line argument what/where that file should be written to.

Ok I got it, thank you for your help
