### ISSUE TITLE
transportModeAssignment

### ISSUE THREAD

**Issue by convelming** [matsim-org/pt2matsim#192]
It seems that using: 
PublicTransitMappingConfigGroup pc = new PublicTransitMappingConfigGroup ();
Map<String, Set<String>> transportModeAssignment = new HashMap<>();
        Set<String> mode1 = new HashSet<>();mode1.add("car");
        transportModeAssignment.put("scheduleMode",mode1);
        mode1.add("bus");
        transportModeAssignment.put("networkModes",mode1);
        pc.setTransportModeAssignment(transportModeAssignment);
        pc.writeToFile("ptMapperConfig.xml");
could not write to file like following
 <parameterset type="transportModeAssignment" >
			
			<param name="networkModes" value="car,bus" />
			<param name="scheduleMode" value="bus" />
</parameterset>
as expected? Is there something wrong with the code above?

**Comment by convelming** [comment]
parameterset type="transportModeAssignment"  was not written

**Comment by polettif** [comment]
You need to create the transportModeAssignment as a new `TransportModeAssignment` object instead of a HashMap and add it as a paramterset. Like in [createDefaultConfig()](https://github.com/matsim-org/pt2matsim/blob/1007ac5c281096d6821559d9a7506c0f67c14981/src/main/java/org/matsim/pt2matsim/config/PublicTransitMappingConfigGroup.java#L97-L109C2):

```java
PublicTransitMappingConfigGroup config = new PublicTransitMappingConfigGroup();
config.getModesToKeepOnCleanUp().add("car");

TransportModeAssignment tmaBus = new TransportModeAssignment("bus");
tmaBus.setNetworkModesStr("car,bus");
TransportModeAssignment tmaRail = new TransportModeAssignment("rail");
tmaRail.setNetworkModesStr("rail,light_rail");
config.addParameterSet(tmaBus);
config.addParameterSet(tmaRail);
```
