### ISSUE TITLE
23.4 release on repo.matsim.org

### ISSUE THREAD

**Issue by manserpa** [matsim-org/pt2matsim#195]
Hi,
First of all, really cool and useful repo!

We wanted to update our `pt2matsim` dependency to the latest available tag.
However, we were not successful in downloading the dependency through maven in the described way. Older tags work perfectly fine.
Looking at the ([release server](https://repo.matsim.org/service/rest/repository/browse/matsim/org/matsim/pt2matsim/)), it seems like 23.4 is not listed. Could it be possible that something in the release process went lost or are we missing something?

Cheers!

**Comment by polettif** [comment]
Looks like the deployment Github action has not worked as intended. I triggered a release manually in e929e7644629125334004643313f15c1c6d5d7fa It worked, as far as I can tell

**Comment by polettif** [comment]
Looks like there were some brackets missing (fixed in 9a8a8ed). We'll monitor this when a new release is due.

**Comment by manserpa** [comment]
Fantastic, all working now. Thanks for this fast support!
