### ISSUE TITLE
Strange and different speeds for one osm way id

### ISSUE THREAD

**Issue by subrina0013** [matsim-org/pt2matsim#196]
Hi

I am just wondering why some links with same osm way id have very different speed limit? For example, here the same osm id has 101 and 6.9 as freespeed. Why is that? It looks wrong and What should I do?

![275902984-b5b748ef-3f73-4bb8-ac29-20214477d575](https://github.com/matsim-org/pt2matsim/assets/42855310/db6414ce-0041-4e03-a176-17c7a68c7222)

**Comment by mrieser** [comment]
Just a guess: There is a bus route on that link. The free speed gets adapted such that the bus is able to drive from one stop to the next in the time according to the schedule. As the schedule is often rounded to full minutes only, this might create artificially high speeds. Even more, if the data in the schedule might be wrong (e.g. unrealistically short travel times between stops according to schedule)

**Comment by subrina0013** [comment]
Oh Thank you so much for the explanation.
