### ISSUE TITLE
Seeking assistance with configuring a suitable setup for config file for a multimodal scenario using a multimodal network generated by pt2matsim

### ISSUE THREAD

**Issue by ArezHK** [matsim-org/pt2matsim#197]
Hello,

I used pt2matsim to generate a MATSim network with links that allow transport modes such as pt, car, and bus, along with artificial links for rail. I intend to run my simulation using subtour mode choice, enabling people to choose between car and pt (bus or train). I want cars and buses to physically run on the network, and trains to follow their specified artificial links. Could you please guide me on which parameters and modules to adjust in my config file for this setup? It seems a bit confusing due to the various teleportation parameters for pt and other modes. Additionally, pt can be either routed on the network like a bus or on artificial links, and I'm uncertain if the latter are considered teleported or not.

I also attempted to run a multimodal scenario, incorporating subtour mode choice. However, I noticed that some agents end up walking long distances without using any available modes (pt or car). What could be the issue here?

I would appreciate your assistance with these questions.

**Comment by polettif** [comment]
Unfortunately I cannot help with this issue and subtour mode choice is not really within the scope of pt2matsim. [matsim-code-examples](https://github.com/matsim-org/matsim-code-examples/issues) seems a better place to ask this.
