### ISSUE TITLE
Disconnected Loop Links

### ISSUE THREAD

**Issue by sfwatergit** [matsim-org/pt2matsim#2]
Hi,

I've found that after mapping, some stop facility nodes created with loop links appear to be disconnected from the network. This creates runtime errors upon routing. I can inspect the source link of the referenced routing problem in VIA using the routing tool as well as zooming in close. A nearby loop-link does seem to be connected. See attached screenshots.  

Manually inspecting a few other links in the network, I've found that several nodes are affected in this way.

Best,

Sid

<img width="958" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20248329/b04ebcb2-a996-11e6-8e3e-9805bedcc5ea.png">

<img width="1000" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20248344/051b3cca-a997-11e6-9bdc-219b2ff1144c.png">

<img width="1104" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20248358/38571910-a997-11e6-9727-c0957ec56b64.png">

**Comment by polettif** [comment]
I haven't encountered this problem so far and couldn't reproduce it with some data sets available to me. Can you provide parts of the unmapped network/schedule where this appears?

**Comment by mrieser** [comment]
> created with loop links appear to be disconnected from the network

Note that this might just be a visualization issue. Via visualizes loop-links as small circles, as you observed. In addition, links have by default a small offset, such that two links running in opposite directions are not exactly on top of each other. The "disconnect" you observe might be due to this offset.

Try to also show the nodes in Via, and change the offset a bit to see how the links move left/right depending on the offset, and potentially touch the loop-link at one setting or another.

**Comment by sfwatergit** [comment]
I don't think it's a visualization issue. Comparing similar artificial bus stop nodes to each other, one routes out:
<img width="1133" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20281190/5a91a6ee-aa64-11e6-86ca-ff8bfe9baed3.png">

And the other doesn't:

<img width="1026" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20281230/86128f4a-aa64-11e6-978b-21e7ebf0b0d0.png">

These are the same nodes visualized earlier. I can make the nodes and loop links touch for the problem node:

<img width="1402" alt="senozon_via" src="https://cloud.githubusercontent.com/assets/1607349/20281318/e9f6c882-aa64-11e6-95b5-93611f028b0f.png">

But this doesn't solve the problem in the simulation itself. I was able to work around this by extending and instrumenting the TransitRouter and UmlaufInterpolator to log the problematic nodes, inferring the corresponding stops, and then removing them from the schedule via a separate utility:

<img width="714" alt="myumlaufinterpolator_java_-_ucb_smartcities_all_-____current_code_java_research_ucb_smartcities_all_" src="https://cloud.githubusercontent.com/assets/1607349/20281430/557f66fe-aa65-11e6-90ed-ea311ed2be54.png">

In all, out of ~540 lines (merging about 12 GTFS datasets), I ended up removing about 30 due to this issue. It would be great to retain those lines. Let me know if there is other info that I can provide.

**Comment by sfwatergit** [comment]
I'll try to provide some of the schedule and network later today. The files are quite large. Should I just provide a dropbox link?

**Comment by polettif** [comment]
Does the issue still come up? Any way to share the files is ok I guess.
