### ISSUE TITLE
new pt2matsim release?

### ISSUE THREAD

**Issue by ikaddoura** [matsim-org/pt2matsim#207]
Thanks for updating to the latest MATSim release. Is there also a new relase for pt2matsim planned? I would need it rather today than tomorrow. :-)

**Comment by marecabo** [comment]
@ikaddoura New release is there!

I cannot deploy to the MATSim Maven Repository, so when @polettif finds the time to deploy, it should be there soon after.

**Comment by polettif** [comment]
Deployments happen automatically via Github actions when a release tag is created: https://github.com/matsim-org/pt2matsim/actions/runs/8813172343/job/24190356039

**Comment by ikaddoura** [comment]
Thank you!!!
