### ISSUE TITLE
Reenable Dependabot

### ISSUE THREAD

**Issue by marecabo** [matsim-org/pt2matsim#221]
@polettif Can you check if dependabot is still active for this repository? I have not seen any PRs by it lately.

**Comment by polettif** [comment]
I don't have access to the repository settings and according to the [security tab](https://github.com/matsim-org/pt2matsim/security) it should be active. I don't know what the issue (if there is one) might be.

**Comment by marecabo** [comment]
Thank you @mrieser for enabling the Dependabot PRs again! 🚀
