### ISSUE TITLE
TransitRouterNetwork:433 add transfer links -> GC overhead limit

### ISSUE THREAD

**Issue by stelehm** [matsim-org/pt2matsim#29]
Hello,

I am trying to run Matsim using the network.xml, schedule.xml and vehicles.xml, which I created with pt2matsim.
Matsim reads the files and starts to create a transit network. This works until it reaches the point "ransitRouterNetwork:433 add transfer links", where it stays for (quite) a while and then stops with an error message, that says it reached the GC overhead limit.
The network is not really big and I used 1/6/12 gb memory, all with the same result.
After asking the Matsim-FAQ, I got the respond that the coordinates of my stop facilities seem to be too close.

Is this problem known, and/or is there a way to configure pt2matsim in a way that building the TransitRouterNetwork does not need that much memory?

Thank you for the help & kind regards

**Comment by polettif** [comment]
The problem might be, as you said in #31, that the coordinates have not been transformed. MATSim assumes a cartesian coordinate system, so the lat/lon values used for WGS84 lead to incredibly small "distances" which then cannot be used properly by the transitrouter.

**Comment by polettif** [comment]
I did check with your FAQ submission, the bug has been fixed.
