### ISSUE TITLE
Coordinate transformation during schedule building not working

### ISSUE THREAD

**Issue by stelehm** [matsim-org/pt2matsim#31]
Hello,

I created my transit schedule with the following command:
`java -cp pt2matsim-18.1.1-shaded.jar org.matsim.pt2matsim.run.Gtfs2TransitSchedule input/gtfs "dayWithMostServices" "EPSG:2154" input/interm/schedule.xml input/interm/vehicles.xml`
This runs without error messages, but after checking the coordinates of my stopping facilities, I noticed that they where still in WGS84. 
As a test, I inserted a wrongly formatted coordinate system (say just "2154") and got an error at org.matsim.core.utils.geometry.transformations.TransformationFactory.getCoordinateTransformation.
So the transformation procedure seems to be called correctly but somehow afterwards isn't applied to the outputs.
I was thinking, this might be causing #29 because the network and schedule end up being in different coordinate systems.

**Comment by polettif** [comment]
I actually came across this issue last week and should've been fixed by [0a89148...](https://github.com/matsim-org/pt2matsim/commit/0a89148b48f745860ffced5a5cdc8b8a3c1cd919). However, it's not in the release version yet.
