### ISSUE TITLE
Update to TransitSchedule_v2

### ISSUE THREAD

**Issue by polettif** [matsim-org/pt2matsim#36]
https://github.com/matsim-org/matsim/pull/191

**Comment by jlieberherr** [comment]
Hi Flavio, I would like to use pt2matsim together with the new possibilities in TransitSchedule_v2, especially the transfer times per stop. For this i guess pt2matsim has to be updated to matsim-0.10 and the new TransitSchedue_v2 specification.
Are there any plans to do that? If not I would tackle this in a new branch in the next days.

**Comment by polettif** [comment]
No, there are no concrete plans to do this yet. So any help would be greatly appreciated!

Concerning switching to matsim 0.10: I planned to do this with the upcoming v18.4-snapshot. This means updating the pom and fixing obvious import errors, nothing further.

**Comment by jlieberherr** [comment]
Hi Fabio, in feature/transfer-time-per-stop I switched to matsim-0.10 (not sure if these changes are as you want them to be) and extended the HafasConverter to the new minimal transfer times. For me it does the job, hopefully you can reuse the work if you migrate to matsim-0.10.

**Comment by polettif** [comment]
Looks good to me, thanks! I'll merge the changes via pull request.
