### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#5]
In order to keep pt2matsim compatible with matsim, I propose the following scheme:

- The master branch of pt2matsim is always keeping track of the master in Matsim, i.e. the dependency in the pom.xml always points towards the latest matsim development version.
- For distinct MATSim releases, a tag is created here just as is done in the main Matsim repository. The pom.xml at this tag is locked to the corresponding version of MATSim.

Furthermore it might make sense to not only get the version right in the pom.xml for the master branch, but to directly link to the MATSim SCM for the latest version (though I did not look into that yet).

If this is appreciated I can set this up.

**Comment by polettif** [comment]
Greatly appreciated, thanks!
