### ISSUE TITLE
Clean fields on read

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/pt2matsim#54]
I have a `stop_times.txt` file with the following first line,

```txt
trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
137737, 5:20:00,5:20:00,1892,1,,0,0,
```
Turns out the space in front of the ` 5:20:00` broke pt2matsim [here](https://github.com/matsim-org/pt2matsim/blob/1a88d0133d61fc74c28e62b8f150028e5509178b/src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java#L493):

```java
int arrivalTime = (int) Time.parseTime(line[col.get(GtfsDefinitions.ARRIVAL_TIME)]);
```

Because this isn't expecting and can't handle the white space. I don't know if this is something you want to handle, or if you just chalk this up to a bad file.

**Comment by polettif** [comment]
Good question... Arrival times [should not be padded with whitespace](https://developers.google.com/transit/gtfs/reference/#stop_timestxt) and I don't really like using [workarounds to handle invalid gtfs feeds](https://github.com/matsim-org/pt2matsim/pull/3). With that being said, cleaning feeds by hand before converting is tedious and simply trimming the input string should fix this issue.

**Comment by gregmacfarlane** [comment]
If only everyone actually followed GTFS as, you know, a specification...
