### ISSUE TITLE
Add -sources.jar to repository?

### ISSUE THREAD

**Issue by dts-ait** [matsim-org/pt2matsim#74]
It would be great if you could build the releases so that also a sources .jar is built and stored on http://dl.bintray.com/polettif/matsim/org/matsim/pt2matsim/ - as it is done with matsim itself (see https://dl.bintray.com/matsim/matsim/org/matsim/matsim/0.10.1/)

Thank you!

**Comment by polettif** [comment]
Should be deployed with v18.12
