### ISSUE TITLE
More advanced network cleaning

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#80]
This issue mainly affects the `cleanNetwork` method:
https://github.com/matsim-org/pt2matsim/blob/master/src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java#L608

Right now it is rather static:
- First a car network is created (with all "car" links)
- Second, a bus network is created (with all "car" or "bus" links)
- Third, a network with everything that has neither bus nor car is created
- Finally, they are all merged on top of each other

I think in general it would be good to configure this in a way like:
```
<parameterset type="networkLayer">
   <param name="allowedTransportModes" value="car" />
   <param name="layerMode" value="car" />
</parameterset>

<parameterset type="networkLayer">
   <param name="allowedTransportModes" value="car,bus" />
   <param name="layerMode" value="bus" />
</parameterset>
```

Then the `cleanNetwork` would do:
- Create a clean network for each `networkLayer`
- Create a rest network with all links that contain modes that are not defined as a layerMode
- Merge them into one big network

What is achieved then is two things:
- All modes that are defined as a `layerMode` have a consistent network (i.e. which can be used for routing etc.)
- All other links are still contained in the network, but they are allowed to contain sinks and sources (e.g. rail or tram), but all `layerMode`s are removed from those links (because initially we saw that they are not consistent with the clean network... otherwise they will be there anyway).

Just to give some context: My current use case was, that we include a `car_passenger` mode in the network, which basically just means everywhere where we have `car` also car passengers can go. Until now, we were always adding this mode directly before the simulation to all `car` links. Now I wanted to put it directly in the network generation. The problem is that currently the `cleanNetwork` makes sure that there is a clean `car` network and a clean `bus` network, but it does not make sure for other modes.

What do you think? Am I missing something?

**Comment by polettif** [comment]
Sounds like a solid approach to me, thank you.

The only thing I'd change is the wording, using "layer" might be a bit confusing. I'd like to make clear that there are routable/consistent networks _within_ the final network and not on top of each other. Just as an idea, how about

```xml
<parameterset type="cleanSubNetwork">
   <param name="allowedTransportModes" value="car,bus" />
   <param name="subNetworkTransportMode" value="bus" />
</parameterset>
```
And call the configGroup `CleanSubNetworkParams` instead of `NetworkLayerParams`. Or is there another word for subnetwork? Something "consistent" maybe... 

Just to be clear, if we use two parametersets (for car and bus) we basically have the same behaviour as of now?

**Comment by sebhoerl** [comment]
Yes, I agree, maybe `routableSubNetwork` ?

> Just to be clear, if we use two parametersets (for car and bus) we basically have the same behaviour as of now?
Exactly.

**Comment by polettif** [comment]
> Yes, I agree, maybe `routableSubNetwork` ?

👍
