### ISSUE TITLE
Infinity freespeed

### ISSUE THREAD

**Issue by josiekre** [matsim-org/pt2matsim#93]
With version 18.7, I'm getting a freespeed of Infinity on some (but not all) artificial bus links. I have never seen this before.

I build my own schedule using a different library but use `pt2matsim` for its `PTMapper.mapScheduleToNetwork()`.

```
<link id="pt_f-dq9-hrt_0364_57620" from="pt_f-dq9-hrt_0364" to="10396" length="21.800366456967428" freespeed="Infinity" capacity="9999.0" permlanes="1.0" oneway="1" modes="bus,artificial" >
```

Any ideas what causes this?

How does MATSim handle a freespeed of Infinity?

(cc: @mrieser)

**Comment by josiekre** [comment]
It looks like artificial links are created with a freespeed set to 1. I cannot see where this changes.

https://github.com/matsim-org/pt2matsim/blob/449f3f5fef54b99407cbaaccbeb4bd157df1395d/src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoGraphImpl.java#L180

**Comment by gregmacfarlane** [comment]
My understanding is that the travel time between bus stops is determined by the MATSim `transitSchedule.xml.gz` file in cases where the vehicle is traveling ahead of traffic. So the vehicle might traverse a transit-only link instantly, but it won't leave the next stop before it is scheduled to leave. I might be wrong about this, and would love to be corrected if I am.

**Comment by polettif** [comment]
> So the vehicle might traverse a transit-only link instantly

Probably. Hard to say without the schedule but I guess is that the problem happens in `ScheduleTools.setFreeSpeedBasedOnSchedule()`

https://github.com/matsim-org/pt2matsim/blob/344f8f4e4165515ebe687d8171cf1279ce9c1946/src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java#L603-L604

which is called towards the end of mapScheduleToNetwork, after artificial links have been created. It's possible the schedule has  stops with the same arrival time and thus no travel time between them.

@josiekre Is there a speficic reason you still use v18.7?

**Comment by josiekre** [comment]
@polettif We have not had a chance to update to a new version and test it. There's no other reason than that. We use MATSim in a docker environment within which we keep versions fixed. This helps to make things reproducible and tractable over time.

**Comment by polettif** [comment]
> Is there an improvement related to this in newer versions?

No not that I'm aware of, I was just curious. It's probably a problem (no time difference between some stops) with the original schedule, maybe even before converting it to MATSim. So it depends on how you built the schedule you used. However, I don't know wheter infinite speed is even a problem in a simulation. 

As for pt2matsim A `minimalTimeOffset` parameter would be possible for GtfsConverter, but I don't think adding this as a default is reasonable as it might have other unintended consequences. The easier solution might be to cap `theoreticalMinSpeed` to 180 km/h (or something like that).

**Comment by josiekre** [comment]
@polettif I've since run the simulations with these Infinity values. I actually converted them to 999999 so that geojson would not baulk. But the scenarios ran without problem. I will close.
